# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e759249d98fc0cea9bf869e91e30a53bb202edec9e7e74bcf10fbfd5e4237d983f3bd710e2e5616190745dc2fab462a25d66d8b86cb067d87bebf236ae813727

test:
  secret_key_base: c81290d181d38847c17f3d37316bfce6b1be3bcb9652e1ca2e0e25e19939dffa5438092566c07d21e548267f92d757eaf05e7b081fdbbcc275494a74d64e17ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
